config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :guide_packs

  resources :guides

  resources :guide_images

  resources :id_maps

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/guide_image.rb
class GuideImage < ActiveRecord::Base
  belongs_to :guide_pack_version
end

app/controllers/guide_images_controller.rb
class GuideImagesController < ApplicationController
  before_action :set_guide_image, only: [:show, :edit, :update, :destroy]

  # GET /guide_images
  # GET /guide_images.json
  def index
    @guide_images = GuideImage.all
  end

  # GET /guide_images/1
  # GET /guide_images/1.json
  def show
  end

  # GET /guide_images/new
  def new
    @guide_image = GuideImage.new
  end

  # GET /guide_images/1/edit
  def edit
  end

  # POST /guide_images
  # POST /guide_images.json
  def create
    @guide_image = GuideImage.new(guide_image_params)

    respond_to do |format|
      if @guide_image.save
        format.html { redirect_to @guide_image, notice: 'Guide image was successfully created.' }
        format.json { render :show, status: :created, location: @guide_image }
      else
        format.html { render :new }
        format.json { render json: @guide_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guide_images/1
  # PATCH/PUT /guide_images/1.json
  def update
    respond_to do |format|
      if @guide_image.update(guide_image_params)
        format.html { redirect_to @guide_image, notice: 'Guide image was successfully updated.' }
        format.json { render :show, status: :ok, location: @guide_image }
      else
        format.html { render :edit }
        format.json { render json: @guide_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guide_images/1
  # DELETE /guide_images/1.json
  def destroy
    @guide_image.destroy
    respond_to do |format|
      format.html { redirect_to guide_images_url, notice: 'Guide image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide_image
      @guide_image = GuideImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_image_params
      params.require(:guide_image).permit(:guide_pack_version_id, :path, :title, :description, :manifest_version)
    end
end

app/helpers/guide_images_helper.rb
module GuideImagesHelper
end

app/views/guide_images/_form.html.erb
<%= simple_form_for(@guide_image) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :guide_pack_version %>
    <%= f.input :path %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :manifest_version %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/guide_images/edit.html.erb
<h1>Editing guide_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide_image %> |
<%= link_to 'Back', guide_images_path %>

app/views/guide_images/index.html.erb
<h1>Listing guide_images</h1>

<table>
  <thead>
    <tr>
      <th>Guide pack version</th>
      <th>Path</th>
      <th>Title</th>
      <th>Description</th>
      <th>Manifest version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guide_images.each do |guide_image| %>
      <tr>
        <td><%= guide_image.guide_pack_version %></td>
        <td><%= guide_image.path %></td>
        <td><%= guide_image.title %></td>
        <td><%= guide_image.description %></td>
        <td><%= guide_image.manifest_version %></td>
        <td><%= link_to 'Show', guide_image %></td>
        <td><%= link_to 'Edit', edit_guide_image_path(guide_image) %></td>
        <td><%= link_to 'Destroy', guide_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide image', new_guide_image_path %>

app/views/guide_images/new.html.erb
<h1>New guide_image</h1>

<%= render 'form' %>

<%= link_to 'Back', guide_images_path %>

app/views/guide_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guide pack version:</strong>
  <%= @guide_image.guide_pack_version %>
</p>

<p>
  <strong>Path:</strong>
  <%= @guide_image.path %>
</p>

<p>
  <strong>Title:</strong>
  <%= @guide_image.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @guide_image.description %>
</p>

<p>
  <strong>Manifest version:</strong>
  <%= @guide_image.manifest_version %>
</p>

<%= link_to 'Edit', edit_guide_image_path(@guide_image) %> |
<%= link_to 'Back', guide_images_path %>