config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :guide_packs

  resources :guides

  resources :guide_images

  resources :id_maps

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/id_map.rb
class IdMap < ActiveRecord::Base
  belongs_to :guide_pack_version
  has_many :meta_conditions
end

app/controllers/id_maps_controller.rb
class IdMapsController < ApplicationController
  before_action :set_id_map, only: [:show, :edit, :update, :destroy]

  # GET /id_maps
  # GET /id_maps.json
  def index
    @id_maps = IdMap.all
  end

  # GET /id_maps/1
  # GET /id_maps/1.json
  def show
  end

  # GET /id_maps/new
  def new
    @id_map = IdMap.new
  end

  # GET /id_maps/1/edit
  def edit
  end

  # POST /id_maps
  # POST /id_maps.json
  def create
    @id_map = IdMap.new(id_map_params)

    respond_to do |format|
      if @id_map.save
        format.html { redirect_to @id_map, notice: 'Id map was successfully created.' }
        format.json { render :show, status: :created, location: @id_map }
      else
        format.html { render :new }
        format.json { render json: @id_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /id_maps/1
  # PATCH/PUT /id_maps/1.json
  def update
    respond_to do |format|
      if @id_map.update(id_map_params)
        format.html { redirect_to @id_map, notice: 'Id map was successfully updated.' }
        format.json { render :show, status: :ok, location: @id_map }
      else
        format.html { render :edit }
        format.json { render json: @id_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /id_maps/1
  # DELETE /id_maps/1.json
  def destroy
    @id_map.destroy
    respond_to do |format|
      format.html { redirect_to id_maps_url, notice: 'Id map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_id_map
      @id_map = IdMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def id_map_params
      params.require(:id_map).permit(:guide_pack_version_id, :guide_id, :game_id)
    end
end

app/helpers/id_maps_helper.rb
module IdMapsHelper
end

app/views/id_maps/_form.html.erb
<%= simple_form_for(@id_map) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :guide_pack_version %>
    <%= f.input :guide_id %>
    <%= f.input :game_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/id_maps/edit.html.erb
<h1>Editing id_map</h1>

<%= render 'form' %>

<%= link_to 'Show', @id_map %> |
<%= link_to 'Back', id_maps_path %>

app/views/id_maps/index.html.erb
<h1>Listing id_maps</h1>

<table>
  <thead>
    <tr>
      <th>Guide pack version</th>
      <th>Guide</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @id_maps.each do |id_map| %>
      <tr>
        <td><%= id_map.guide_pack_version %></td>
        <td><%= id_map.guide_id %></td>
        <td><%= id_map.game_id %></td>
        <td><%= link_to 'Show', id_map %></td>
        <td><%= link_to 'Edit', edit_id_map_path(id_map) %></td>
        <td><%= link_to 'Destroy', id_map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Id map', new_id_map_path %>

app/views/id_maps/new.html.erb
<h1>New id_map</h1>

<%= render 'form' %>

<%= link_to 'Back', id_maps_path %>

app/views/id_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guide pack version:</strong>
  <%= @id_map.guide_pack_version %>
</p>

<p>
  <strong>Guide:</strong>
  <%= @id_map.guide_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @id_map.game_id %>
</p>

<%= link_to 'Edit', edit_id_map_path(@id_map) %> |
<%= link_to 'Back', id_maps_path %>