config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :guide_packs

  resources :guides

  resources :guide_images

  resources :id_maps

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/guide.rb
class Guide < ActiveRecord::Base
  belongs_to :guide_pack_version
  belongs_to :guide_image
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show, :edit, :update, :destroy]

  # GET /guides
  # GET /guides.json
  def index
    @guides = Guide.all
  end

  # GET /guides/1
  # GET /guides/1.json
  def show
  end

  # GET /guides/new
  def new
    @guide = Guide.new
  end

  # GET /guides/1/edit
  def edit
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(guide_params)

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render :show, status: :created, location: @guide }
      else
        format.html { render :new }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/1
  # PATCH/PUT /guides/1.json
  def update
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { render :show, status: :ok, location: @guide }
      else
        format.html { render :edit }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url, notice: 'Guide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide
      @guide = Guide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_params
      params.require(:guide).permit(:guide_pack_version_id, :path, :title, :guide_image_id, :content, :manifest_version)
    end
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_form.html.erb
<%= simple_form_for(@guide) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :guide_pack_version %>
    <%= f.input :path %>
    <%= f.input :title %>
    <%= f.association :guide_image %>
    <%= f.input :content %>
    <%= f.input :manifest_version %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/guides/edit.html.erb
<h1>Editing guide</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide %> |
<%= link_to 'Back', guides_path %>

app/views/guides/index.html.erb
<h1>Listing guides</h1>

<table>
  <thead>
    <tr>
      <th>Guide pack version</th>
      <th>Path</th>
      <th>Title</th>
      <th>Guide image</th>
      <th>Content</th>
      <th>Manifest version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guides.each do |guide| %>
      <tr>
        <td><%= guide.guide_pack_version %></td>
        <td><%= guide.path %></td>
        <td><%= guide.title %></td>
        <td><%= guide.guide_image %></td>
        <td><%= guide.content %></td>
        <td><%= guide.manifest_version %></td>
        <td><%= link_to 'Show', guide %></td>
        <td><%= link_to 'Edit', edit_guide_path(guide) %></td>
        <td><%= link_to 'Destroy', guide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide', new_guide_path %>

app/views/guides/new.html.erb
<h1>New guide</h1>

<%= render 'form' %>

<%= link_to 'Back', guides_path %>

app/views/guides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guide pack version:</strong>
  <%= @guide.guide_pack_version %>
</p>

<p>
  <strong>Path:</strong>
  <%= @guide.path %>
</p>

<p>
  <strong>Title:</strong>
  <%= @guide.title %>
</p>

<p>
  <strong>Guide image:</strong>
  <%= @guide.guide_image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @guide.content %>
</p>

<p>
  <strong>Manifest version:</strong>
  <%= @guide.manifest_version %>
</p>

<%= link_to 'Edit', edit_guide_path(@guide) %> |
<%= link_to 'Back', guides_path %>