config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :guide_packs

  resources :guides

  resources :guide_images

  resources :id_maps

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/guide_pack.rb
class GuidePack < ActiveRecord::Base
  has_many :guide_pack_versions
  has_and_belongs_to_many :users
end

app/controllers/guide_packs_controller.rb
class GuidePacksController < ApplicationController
  before_action :set_guide_pack, only: [:show, :edit, :update, :destroy]

  # GET /guide_packs
  # GET /guide_packs.json
  def index
    @guide_packs = GuidePack.all
  end

  # GET /guide_packs/1
  # GET /guide_packs/1.json
  def show
  end

  # GET /guide_packs/new
  def new
    @guide_pack = GuidePack.new
  end

  # GET /guide_packs/1/edit
  def edit
  end

  # POST /guide_packs
  # POST /guide_packs.json
  def create
    @guide_pack = GuidePack.new(guide_pack_params)

    respond_to do |format|
      if @guide_pack.save
        format.html { redirect_to @guide_pack, notice: 'Guide pack was successfully created.' }
        format.json { render :show, status: :created, location: @guide_pack }
      else
        format.html { render :new }
        format.json { render json: @guide_pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guide_packs/1
  # PATCH/PUT /guide_packs/1.json
  def update
    respond_to do |format|
      if @guide_pack.update(guide_pack_params)
        format.html { redirect_to @guide_pack, notice: 'Guide pack was successfully updated.' }
        format.json { render :show, status: :ok, location: @guide_pack }
      else
        format.html { render :edit }
        format.json { render json: @guide_pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guide_packs/1
  # DELETE /guide_packs/1.json
  def destroy
    @guide_pack.destroy
    respond_to do |format|
      format.html { redirect_to guide_packs_url, notice: 'Guide pack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide_pack
      @guide_pack = GuidePack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_pack_params
      params.require(:guide_pack).permit(:packid, :pretty_name, :description, :is_private)
    end
end

app/helpers/guide_packs_helper.rb
module GuidePacksHelper
end

app/views/guide_packs/_form.html.erb
<%= simple_form_for(@guide_pack) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :packid %>
    <%= f.input :pretty_name %>
    <%= f.input :description %>
    <%= f.input :is_private %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/guide_packs/edit.html.erb
<h1>Editing guide_pack</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide_pack %> |
<%= link_to 'Back', guide_packs_path %>

app/views/guide_packs/index.html.erb
<h1>Listing guide_packs</h1>

<table>
  <thead>
    <tr>
      <th>Packid</th>
      <th>Pretty name</th>
      <th>Description</th>
      <th>Is private</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guide_packs.each do |guide_pack| %>
      <tr>
        <td><%= guide_pack.packid %></td>
        <td><%= guide_pack.pretty_name %></td>
        <td><%= guide_pack.description %></td>
        <td><%= guide_pack.is_private %></td>
        <td><%= link_to 'Show', guide_pack %></td>
        <td><%= link_to 'Edit', edit_guide_pack_path(guide_pack) %></td>
        <td><%= link_to 'Destroy', guide_pack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide pack', new_guide_pack_path %>

app/views/guide_packs/new.html.erb
<h1>New guide_pack</h1>

<%= render 'form' %>

<%= link_to 'Back', guide_packs_path %>

app/views/guide_packs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Packid:</strong>
  <%= @guide_pack.packid %>
</p>

<p>
  <strong>Pretty name:</strong>
  <%= @guide_pack.pretty_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @guide_pack.description %>
</p>

<p>
  <strong>Is private:</strong>
  <%= @guide_pack.is_private %>
</p>

<%= link_to 'Edit', edit_guide_pack_path(@guide_pack) %> |
<%= link_to 'Back', guide_packs_path %>